### ISSUE TITLE
I'm having an issue with my coding

### ISSUE THREAD

**Issue by DoaaDhaif** [DoaaDhaif/dinosaur-designs#1]
![image](https://user-images.githubusercontent.com/43138805/46384642-2f38c600-c685-11e8-9f05-9b4b953176a1.png)
![image](https://user-images.githubusercontent.com/43138805/46384674-6e671700-c685-11e8-9cb0-0d4e6291694c.png)

**Comment by DoaaDhaif** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
*Line 7—*
The semi-colon (`;`) is where a colon (`:`) should be and the semi-colon is missing at the end of the line.

*Iguanodon—*
It’s spelled wrong.
